# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Velox Backend Weekly Job

on:
  pull_request:
    paths:
      - '.github/workflows/velox_weekly.yml'
      - 'build/mvn'
      - 'ep/build-velox/src/**'
  schedule:
    - cron: '0 20 * * 0'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  weekly-build-on-openeuler:
    if: ${{ startsWith(github.repository, 'apache/') }}
    runs-on: ubuntu-24.04-arm
    container: openeuler/openeuler:24.03
    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          dnf install -y --disablerepo='update*' --disablerepo='*source*' --disablerepo='*debuginfo*' \
            java-1.8.0-openjdk-devel sudo patch git perl ccache curl python3
          echo "JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk" >> "$GITHUB_ENV"
      - name: Build
        run: ./dev/package.sh --spark_version=3.5

  weekly-build-on-macos:
    if: ${{ startsWith(github.repository, 'apache/') }}
    runs-on: macos-15
    env:
      INSTALL_PREFIX: /tmp/deps-install
    steps:
      - uses: actions/checkout@v7
      - name: Set up Java 17
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 17
      - name: Install dependencies
        run: brew install wget pkgconfig ccache
      - name: Build
        run: ./dev/buildbundle-veloxbe.sh --run_setup_script=ON --build_arrow=ON --build_tests=ON --build_benchmarks=ON --spark_version=3.5
